### ISSUE TITLE
Mode Hors ligne

### ISSUE THREAD

**Issue by Link0Darck** [TrxyyDev/AlternativeAPI-launcher#1]
Bonjour Trxyy,
Je voudrais savoir si il était possible d’améliorer ton option mode hors ligne que si l’hébergeur web est en maintenance qu'on ne soit pas obliger de débrancher le cable si on as un pc fixe ou couper le wifi
exemple:
si j'ai un hébergeur web livehost et qui est en maintenance et que mon hébergeur minecraft fonctionne sa serait embêtant de débrancher la cable si sa fonctionne pas

Donc serait possible que si le launcher skip si il arrive pas à acceder sur le site au lieu de couper internet
cordialement

**Comment by Link0Darck** [comment]
salut,
je tien a te dire je vient de refaire mon launcher à la dernière alternative api mais actuellement il y as des problème je peut pas le faire fonctionner sur linux et j'aurais une suggestion as faire concernant un mode offline.
ha oui je précise que j'ai fait les commande est tout sur linux et ce n'ai pas
`java -jar --module-path /user/share/openjfx/lib --add-modules=javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web monlauncher.jar classeMain`

mais plutôt
`java -jar --module-path /usr/share/openjfx/lib --add-modules=javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web monlauncher.jar classeMain`

tu te tromper sur ton forum.

en gros la je suis sur linux le boostrap ne lance pas le launcher obliger de lancer le launcher manuellement
le launcher en 1.15.2 ne fonctionne pas ça marque ceci

`[AUpdater]Il semblerait que vous utilisiez Mac/Linux.
[AUpdater]Si vous rencontrez des difficultÃ©s, rendez-vous sur:
[AUpdater]https://forum.alternative-api.fr/installer-jfx-sur-linux-aapi
[AUpdater]========================================
[AUpdater]|           AlternativeUpdater         |
[AUpdater]|            Version: 1.3.0            |
[AUpdater]========================================
[AAuth]========================================
[AAuth]|            AlternativeAuth           |
[AAuth]|            Version: 1.0.2            |
[AAuth]========================================
[AAuth]Connected Successfully !
[AUpdater]=============UPDATING GAME==============
[AUpdater]Updating Local Minecraft Version.
[AUpdater]========================================
[AUpdater]Getting ignore/delete list   [Step 1/6]
[AUpdater]========================================
[AUpdater]Indexing version              [Step 2/6]
[AUpdater]========================================
[AUpdater]Indexing assets               [Step 3/6]
[AUpdater]========================================
[AUpdater]Indexing custom jars         [3-bonus/6]
[AUpdater]========================================
[AUpdater]Time (delta) to compare resources: 703 ms
[AUpdater]From: http://neko-world.hd.free.fr:81/datas/files/
[AUpdater]Updating assets               [Step 4/6]
[AUpdater]========================================
[AUpdater]Updating jars/libraries       [Step 5/6]
[AUpdater]========================================
[AUpdater]Updating custom jars         [5-bonus/6]
[AUpdater]========================================
[AUpdater]Cleaning installation         [Step 6/6]
[AUpdater]========================================
[AUpdater]========================================
[AUpdater]|      Update Finished. Launching.     |
[AUpdater]|            Version 1.15.2            |
[AUpdater]|          Runtime: 11.0.12          |
[AUpdater]========================================
[AUpdater]


[AUpdater]==============GAME OUTPUT===============
[AUpdater]========================================
[AUpdater]Unpacking natives             [Step 5/7]
[AUpdater]========================================
[AUpdater]Deleting unrequired Natives   [Step 6/7]
[AUpdater]========================================
[AUpdater]Launching: [/usr/lib/jvm/java-11-openjdk-amd64/bin/java, -XX:-UseAdaptiveSizePolicy, -Djava.library.path=/home/linkdarck/.Beta-Neko-World/bin/natives, -Dfml.ignoreInvalidMinecraftCertificates=true, -Dfml.ignorePatchDiscrepancies=true, -Xmx1G, -Xmn128M, -cp, "/home/linkdarck/.Beta-Neko-World/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/ow2/asm/asm-analysis/6.1.1/asm-analysis-6.1.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/org/checkerframework/checker-qual/2.0.0/checker-qual-2.0.0.jar:/home/linkdarck/.Beta-Neko-World/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:/home/linkdarck/.Beta-Neko-World/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/linkdarck/.Beta-Neko-World/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraft/client/1.15.2-20200122.131323/client-1.15.2-20200122.131323-srg.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraft/client/1.15.2/client-1.15.2-extra.jar.cache:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraft/client/1.15.2/client-1.15.2-slim.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraft/client/1.15.2/client-1.15.2-extra.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraft/client/1.15.2/client-1.15.2-slim.jar.cache:/home/linkdarck/.Beta-Neko-World/libraries/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/sf/jopt-simple/jopt-simple/4.9/jopt-simple-4.9.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/md-5/SpecialSource/1.8.5/SpecialSource-1.8.5.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/jodah/typetools/0.6.1/typetools-0.6.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraftforge/jarsplitter/1.1.2/jarsplitter-1.1.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraftforge/installertools/1.1.4/installertools-1.1.4.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraftforge/binarypatcher/1.0.12/binarypatcher-1.0.12.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraftforge/accesstransformers/2.0.0-milestone.1-shadowed/accesstransformers-2.0.0-milestone.1-shadowed.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraftforge/eventbus/2.0.0-milestone.1-service/eventbus-2.0.0-milestone.1-service.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraftforge/forge/1.15.2-31.1.0/forge-1.15.2-31.1.0-client.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraftforge/forge/1.15.2-31.1.0/forge-1.15.2-31.1.0-universal.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraftforge/forge/1.15.2-31.1.0/forge-1.15.2-31.1.0.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraftforge/forgespi/2.0.0-milestone.1/forgespi-2.0.0-milestone.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/net/minecraftforge/coremods/2.0.0-milestone.1/coremods-2.0.0-milestone.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/github/jponge/lzma-java/1.3/lzma-java-1.3.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/electronwill/night-config/core/3.6.2/core-3.6.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/electronwill/night-config/toml/3.6.2/toml-3.6.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/google/guava/guava/25.1-jre/guava-25.1-jre.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/nothome/javaxdelta/2.0.1/javaxdelta-2.0.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar:/home/linkdarck/.Beta-Neko-World/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/linkdarck/.Beta-Neko-World/libraries/de/oceanlabs/mcp/mcp_config/1.15.2-20200122.131323/mcp_config-1.15.2-20200122.131323.zip:/home/linkdarck/.Beta-Neko-World/libraries/de/oceanlabs/mcp/mcp_config/1.15.2-20200122.131323/mcp_config-1.15.2-20200122.131323-mappings.txt:/home/linkdarck/.Beta-Neko-World/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/home/linkdarck/.Beta-Neko-World/libraries/cpw/mods/modlauncher/5.0.0-milestone.4/modlauncher-5.0.0-milestone.4.jar:/home/linkdarck/.Beta-Neko-World/libraries/cpw/mods/grossjava9hacks/1.1.0/grossjava9hacks-1.1.0.jar:/home/linkdarck/.Beta-Neko-World/libraries/trove/trove/1.0.2/trove-1.0.2.jar:/home/linkdarck/.Beta-Neko-World/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/linkdarck/.Beta-Neko-World/bin/minecraft.jar", cpw.mods.modlauncher.Launcher, --username, Player, --version, 1.15.2, --gameDir, /home/linkdarck/.Beta-Neko-World/bin/game, --assetsDir, /home/linkdarck/.Beta-Neko-World/assets, --assetIndex, 1.15, --uuid, a33318f1dc284aeeb0d90a28a8d0e341, --accessToken, ????????, --userType, legacy, --versionType, release, --width=854, --height=480, --launchTarget, fmlclient, --fml.forgeVersion, 31.1.0, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200122.131323]
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Failed to find class associated with library asm
Exception in thread "main" cpw.mods.modlauncher.InvalidLauncherSetupException: Missing classes, cannot continue
	at cpw.mods.modlauncher.ValidateLibraries.validate(ValidateLibraries.java:43)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:63)`
