### ISSUE TITLE
Erreur lancement avec forge

### ISSUE THREAD

**Issue by bouchbi** [TrxyyDev/AlternativeAPI-launcher#2]
Hey, le launcher marche nickel tout est en ordre, sauf la fenêtre forge qui s'ouvre puis qui crash aussitôt.

Je pense avoir tout fait bien dans la classe main:

`private       GameForge           forge       = new GameForge(Forge.DEFAULT, "1.16.5", "36.2.17", "20210115.111550");
	private       GameEngine          engine      = new GameEngine(folder, links, preferences, GameStyle.FORGE_1_13_HIGHER, forge);`

mais j'ai :

`Exception in thread "main" [07:18:10.386] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.IllegalArgumentException 
[07:18:10.386] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39) 
[07:18:10.386] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) 
[07:18:10.386] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) 
[07:18:10.386] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) 
[07:18:10.386] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) 
[07:18:10.387] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.IllegalArgumentException 
[07:18:10.387] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:69) 
[07:18:10.387] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:56) 
[07:18:10.387] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at org.objectweb.asm.tree.ClassNode.<init>(ClassNode.java:150) 
[07:18:10.387] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:71) 
[07:18:10.387] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) 
[07:18:10.387] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) 
[07:18:10.387] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) 
[07:18:10.387] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
[07:18:10.387] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.forName0(Native Method) 
[07:18:10.388] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.forName(Class.java:348) 
[07:18:10.388] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) 
[07:18:10.388] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$433/665512315.call(Unknown Source) 
[07:18:10.388] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) 
[07:18:10.388] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more `

Si je pourrais avoir une petite réponse stpp, ensuite tout sera bon X)

**Comment by bouchbi** [comment]
J'ai trouvé, erreur bête d'inattention j'ai pas mis la même version de forge sur le launcher et dans les librairies
